name: extract-pattern
version: 1.1.0
description: Identify recurring patterns in code, problems, or solutions and document them for reuse
author: adhd8k
agentCompatibility:
  - claude-code
  - cursor
  - aider
  - openclaw
triggers:
  # Phrase-based: user says these things
  - pattern: "I've done this before"
  - pattern: "similar to how we"
  - pattern: "same pattern as"
  - pattern: "recurring issue"
  # Action-based: Claude is doing these things (even silently)
  - action: "Writing logic that mirrors existing code elsewhere in the project"
  - action: "Creating a utility or helper that abstracts repeated boilerplate"
  - action: "Solving a problem in the same way it was solved before"
  - action: "Implementing a second instance of a component, hook, or module type"
  - action: "Finding code that diverges from documented conventions or patterns"
  - action: "Noticing a tool/framework has specific syntax or config patterns worth remembering"
  - action: "Performing a sequence of 3+ steps that form a repeatable workflow"
completion_check: "Is there a reusable pattern here?"
variables:
  patternsDir: "{{projectRoot}}/docs/patterns"
  template: "templates/pattern.md"
  conventionTemplate: "templates/convention-rule.md"
  toolTemplate: "templates/tool-pattern.md"
files:
  - path: "SKILL.md"
    type: "instructions"
  - path: "templates/pattern.md"
    type: "template"
  - path: "templates/convention-rule.md"
    type: "template"
  - path: "templates/tool-pattern.md"
    type: "template"
